# Generated by Django 5.2.4 on 2025-07-16 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='centro_costos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='familias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm_app.centro_costos')),
            ],
        ),
        migrations.CreateModel(
            name='cc_permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm_app.centro_costos')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm_app.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='maestro_de_materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm_app.familias')),
            ],
        ),
        migrations.CreateModel(
            name='VSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField()),
                ('cantidad_entregada', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm_app.maestro_de_materiales')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm_app.empleados')),
            ],
        ),
    ]
