# Generated by Django 5.2.6 on 2025-09-18 12:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='centro_costos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='epp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='maestro_de_materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('clase_sap', models.CharField(max_length=10)),
                ('cantidad_stock', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='nro_tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='perfil_riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm_app.centro_costos')),
                ('nro_tarjeta', models.ManyToManyField(blank=True, to='vsm_app.nro_tarjeta')),
                ('perfil_riesgo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vsm_app.perfil_riesgo')),
            ],
        ),
        migrations.CreateModel(
            name='PermisoRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm_app.centro_costos')),
                ('producto', models.ManyToManyField(to='vsm_app.maestro_de_materiales')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('permisos', models.ManyToManyField(related_name='roles', to='vsm_app.permisos')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('cc_permitidos', models.ManyToManyField(blank=True, related_name='usuarios_permitidos', to='vsm_app.centro_costos')),
                ('empleado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vsm_app.empleados')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vsm_app.roles')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='tags_productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('productos', models.ManyToManyField(related_name='tags', to='vsm_app.maestro_de_materiales')),
            ],
        ),
        migrations.AddField(
            model_name='perfil_riesgo',
            name='tags_productos',
            field=models.ManyToManyField(related_name='perfiles', to='vsm_app.tags_productos'),
        ),
        migrations.CreateModel(
            name='VSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entrega', models.CharField(blank=True, choices=[('INSUMOS', 'Insumos'), ('EPP', 'EPP')], max_length=20, null=True)),
                ('tipo_facturacion', models.CharField(blank=True, choices=[('FACTURADO', 'Facturado'), ('NO_FACTURADO', 'No facturado')], max_length=20, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('observaciones_entrega', models.TextField(blank=True, null=True)),
                ('numero_sap', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('estado_sap', models.CharField(choices=[('procesado', 'Procesado'), ('no_procesado', 'No Procesado'), ('error', 'Error')], default='no_procesado', max_length=20)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('centro_costos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm_app.centro_costos')),
                ('retirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retirante', to='vsm_app.empleados')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VSMProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_entregada', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm_app.maestro_de_materiales')),
                ('vsm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm_app.vsm')),
            ],
        ),
        migrations.AddField(
            model_name='vsm',
            name='productos',
            field=models.ManyToManyField(through='vsm_app.VSMProducto', to='vsm_app.maestro_de_materiales'),
        ),
        migrations.CreateModel(
            name='relacion_cc_perfil_riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False)),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm_app.centro_costos')),
                ('perfil_riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm_app.perfil_riesgo')),
            ],
            options={
                'unique_together': {('centro_costo', 'perfil_riesgo', 'default')},
            },
        ),
    ]
