# Generated by Django 5.2.4 on 2025-07-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsm',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
