# Generated by Django 5.2.4 on 2025-07-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0002_vsm_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vsm',
            old_name='responsable',
            new_name='solicitante',
        ),
    ]
