# Generated by Django 5.2.6 on 2025-09-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0002_alter_permisos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
