# Generated by Django 5.2.6 on 2025-09-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0003_alter_permisos_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags_productos',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='tags_productos',
            name='productos',
        ),
        migrations.AddField(
            model_name='tags_productos',
            name='descripcion',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
