# Generated by Django 5.2.4 on 2025-07-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0003_rename_responsable_vsm_solicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsm',
            name='numero_sap',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
