# Generated by Django 5.2.6 on 2025-09-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0004_remove_tags_productos_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil_riesgo',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='perfil_riesgo',
            name='tags_productos',
            field=models.ManyToManyField(blank=True, default=None, related_name='perfiles', to='vsm_app.tags_productos'),
        ),
    ]
