# Generated by Django 5.2.4 on 2025-07-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0005_permisos_roles_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='permisos',
            field=models.ManyToManyField(related_name='roles', to='vsm_app.permisos'),
        ),
    ]
