# Generated by Django 5.2.4 on 2025-07-29 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0006_alter_roles_permisos'),
    ]

    operations = [
        migrations.CreateModel(
            name='subfamilias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm_app.familias')),
            ],
        ),
    ]
