# Generated by Django 5.2.6 on 2025-10-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0006_vsmproducto_firma_retirante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vsmproducto',
            name='firma_retirante',
        ),
    ]
