# Generated by Django 5.2.6 on 2025-10-07 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0007_remove_vsmproducto_firma_retirante'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsmproducto',
            name='firma_retirante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vsm_app.empleados'),
            preserve_default=False,
        ),
    ]
