# Generated by Django 5.2.4 on 2025-07-29 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0007_subfamilias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestro_de_materiales',
            name='familia',
        ),
        migrations.AddField(
            model_name='maestro_de_materiales',
            name='subfamilia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vsm_app.subfamilias'),
            preserve_default=False,
        ),
    ]
