# Generated by Django 5.2.4 on 2025-07-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0008_remove_maestro_de_materiales_familia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsm',
            name='cantidad_entregada',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
