# Generated by Django 5.2.6 on 2025-10-07 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0008_vsmproducto_firma_retirante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsmproducto',
            name='firma_retirante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firma_retirante', to='vsm_app.empleados'),
        ),
    ]
