# Generated by Django 5.2.6 on 2025-10-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0009_alter_vsmproducto_firma_retirante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='epp',
        ),
    ]
