# Generated by Django 5.2.4 on 2025-07-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0009_alter_vsm_cantidad_entregada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vsm',
            old_name='fecha_creacion',
            new_name='fecha_solicitud',
        ),
        migrations.RemoveField(
            model_name='vsm',
            name='fecha_salida',
        ),
        migrations.AddField(
            model_name='vsm',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vsm',
            name='observaciones_entrega',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vsm',
            name='cantidad_entregada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vsm',
            name='cantidad_solicitada',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vsm',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('parcial', 'Parcial'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
