# Generated by Django 5.2.6 on 2025-10-16 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0010_delete_epp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='cc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vsm_app.centro_costos'),
        ),
        migrations.AlterField(
            model_name='vsmproducto',
            name='firma_retirante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firma_retirante', to='vsm_app.empleados'),
        ),
    ]
