# Generated by Django 5.2.4 on 2025-08-04 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0010_rename_fecha_creacion_vsm_fecha_solicitud_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vsm',
            name='producto',
        ),
        migrations.AlterField(
            model_name='vsm',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VSMProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm_app.maestro_de_materiales')),
                ('vsm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm_app.vsm')),
            ],
        ),
        migrations.AddField(
            model_name='vsm',
            name='productos',
            field=models.ManyToManyField(through='vsm_app.VSMProducto', to='vsm_app.maestro_de_materiales'),
        ),
    ]
