# Generated by Django 5.2.4 on 2025-08-04 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0011_remove_vsm_producto_alter_vsm_solicitante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsm',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm_app.empleados'),
        ),
    ]
