# Generated by Django 5.2.6 on 2025-10-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0011_alter_empleados_cc_alter_vsmproducto_firma_retirante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestro_de_materiales',
            name='cantidad_stock',
        ),
        migrations.AddField(
            model_name='maestro_de_materiales',
            name='almacen',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maestro_de_materiales',
            name='centro',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
