# Generated by Django 5.2.6 on 2025-10-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0012_remove_maestro_de_materiales_cantidad_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='rol',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='permisos',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='vsm_app.permisos'),
        ),
    ]
