# Generated by Django 5.2.6 on 2025-10-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0013_remove_usuarios_rol_usuarios_permisos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
