# Generated by Django 5.2.4 on 2025-08-04 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0013_alter_vsm_solicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsm',
            name='retirante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='retirante', to='vsm_app.empleados'),
            preserve_default=False,
        ),
    ]
