# Generated by Django 5.2.4 on 2025-08-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0014_vsm_retirante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vsmproducto',
            old_name='cantidad',
            new_name='cantidad_solicitada',
        ),
        migrations.RemoveField(
            model_name='vsm',
            name='cantidad_entregada',
        ),
        migrations.RemoveField(
            model_name='vsm',
            name='cantidad_solicitada',
        ),
        migrations.AddField(
            model_name='vsmproducto',
            name='cantidad_entregada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
