# Generated by Django 5.2.6 on 2025-10-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0014_delete_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsmproducto',
            name='firma_retirante',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
    ]
