# Generated by Django 5.2.4 on 2025-08-05 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0015_rename_cantidad_vsmproducto_cantidad_solicitada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsm',
            name='centro_costos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vsm_app.centro_costos'),
            preserve_default=False,
        ),
    ]
