# Generated by Django 5.2.6 on 2025-11-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0015_alter_vsmproducto_firma_retirante'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsm',
            name='anio_documento',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
