# Generated by Django 5.2.4 on 2025-08-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0016_vsm_centro_costos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subfamilias',
            name='familia',
        ),
        migrations.RemoveField(
            model_name='maestro_de_materiales',
            name='subfamilia',
        ),
        migrations.DeleteModel(
            name='familias',
        ),
        migrations.DeleteModel(
            name='subfamilias',
        ),
    ]
