# Generated by Django 5.2.6 on 2025-12-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0016_vsm_anio_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='almacenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almacen', models.CharField(max_length=4)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='maestro_de_materiales',
            name='almacen',
            field=models.CharField(max_length=5),
        ),
    ]
