# Generated by Django 5.2.6 on 2025-12-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0017_almacenes_alter_maestro_de_materiales_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='almacenes_permitidos',
            field=models.ManyToManyField(blank=True, to='vsm_app.almacenes'),
        ),
    ]
