# Generated by Django 5.2.4 on 2025-08-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0017_remove_subfamilias_familia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='epp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='vsm',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
