# Generated by Django 5.2.4 on 2025-08-07 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0018_epp_vsm_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm_app.centro_costos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm_app.maestro_de_materiales')),
            ],
            options={
                'unique_together': {('producto', 'centro_costo')},
            },
        ),
        migrations.AddField(
            model_name='centro_costos',
            name='productos',
            field=models.ManyToManyField(related_name='centros_habilitados', through='vsm_app.PermisoRetiro', to='vsm_app.maestro_de_materiales'),
        ),
    ]
