# Generated by Django 5.2.6 on 2025-12-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0018_usuarios_almacenes_permitidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestro_de_materiales',
            name='almacen',
        ),
    ]
