# Generated by Django 5.2.4 on 2025-08-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0019_permisoretiro_centro_costos_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centro_costos',
            name='productos',
        ),
    ]
