# Generated by Django 5.2.4 on 2025-08-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0020_remove_centro_costos_productos'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permisoretiro',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='centro_costos',
            name='productos',
            field=models.ManyToManyField(related_name='centros_habilitados', through='vsm_app.PermisoRetiro', to='vsm_app.maestro_de_materiales'),
        ),
    ]
