# Generated by Django 5.2.6 on 2025-12-18 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0020_remove_maestro_de_materiales_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestro_de_materiales',
            name='almacen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vsm_app.almacenes'),
        ),
    ]
