# Generated by Django 5.2.6 on 2025-12-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0021_maestro_de_materiales_almacen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacenes',
            name='almacen',
            field=models.CharField(max_length=5),
        ),
    ]
