# Generated by Django 5.2.4 on 2025-08-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0021_alter_permisoretiro_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centro_costos',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='permisoretiro',
            name='producto',
        ),
        migrations.AddField(
            model_name='permisoretiro',
            name='producto',
            field=models.ManyToManyField(to='vsm_app.maestro_de_materiales'),
        ),
    ]
