# Generated by Django 5.2.6 on 2025-12-22 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0022_alter_almacenes_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsm',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vsm_app.almacenes'),
        ),
    ]
