# Generated by Django 5.2.4 on 2025-08-14 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0022_remove_centro_costos_productos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado_CC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm_app.centro_costos')),
                ('empleado', models.ManyToManyField(to='vsm_app.empleados')),
            ],
        ),
    ]
