# Generated by Django 5.2.4 on 2025-08-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0023_empleado_cc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='cc',
        ),
    ]
