# Generated by Django 5.2.6 on 2025-12-22 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0024_empresas_remove_usuarios_almacenes_permitidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacenes',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='almacenes',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vsm_app.empresas'),
        ),
    ]
