# Generated by Django 5.2.4 on 2025-08-15 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0024_remove_empleados_cc'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='cc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vsm_app.centro_costos'),
            preserve_default=False,
        ),
    ]
