# Generated by Django 5.2.6 on 2025-12-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0025_remove_almacenes_descripcion_almacenes_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacenes',
            name='empresa',
        ),
        migrations.AddField(
            model_name='almacenes',
            name='empresa',
            field=models.ManyToManyField(blank=True, to='vsm_app.empresas'),
        ),
    ]
