# Generated by Django 5.2.4 on 2025-08-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vsm_app', '0025_empleados_cc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='active',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='cc_permitidos',
            field=models.ManyToManyField(blank=True, related_name='usuarios_permitidos', to='vsm_app.centro_costos'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
