# Generated by Django 5.2.6 on 2025-12-22 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0026_remove_almacenes_empresa_almacenes_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacenes',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='empresas',
        ),
        migrations.AddField(
            model_name='almacenes',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vsm_app.empresas'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='empresas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_empresas', to='vsm_app.empresas'),
        ),
    ]
