# Generated by Django 5.2.4 on 2025-08-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0026_remove_usuarios_active_usuarios_cc_permitidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='empleado_cc',
            name='centro_costo',
        ),
        migrations.RemoveField(
            model_name='empleado_cc',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='empresa',
        ),
        migrations.DeleteModel(
            name='cc_permisos',
        ),
        migrations.DeleteModel(
            name='Empleado_CC',
        ),
    ]
