# Generated by Django 5.2.4 on 2025-08-18 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0027_tipo_entrega_tipo_facturacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsm',
            name='tipo_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vsm_app.tipo_entrega'),
        ),
        migrations.AddField(
            model_name='vsm',
            name='tipo_facturacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vsm_app.tipo_facturacion'),
        ),
    ]
