# Generated by Django 5.2.6 on 2025-12-23 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0027_remove_almacenes_empresa_remove_usuarios_empresas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='permiso_empresa_almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm_app.almacenes')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm_app.empresas')),
            ],
            options={
                'unique_together': {('empresa', 'almacen')},
            },
        ),
    ]
