# Generated by Django 5.2.4 on 2025-08-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0028_vsm_tipo_entrega_vsm_tipo_facturacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleados',
            old_name='apellido',
            new_name='nro_tarjeta',
        ),
    ]
