# Generated by Django 5.2.6 on 2025-12-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0028_permiso_empresa_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso_empresa_almacen',
            name='empleados_aprobadores',
            field=models.ManyToManyField(blank=True, related_name='empleados_aprobadores', to='vsm_app.empleados'),
        ),
        migrations.AddField(
            model_name='permiso_empresa_almacen',
            name='requiere_aprobacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vsm',
            name='estado_aprobacion',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('pendiente', 'Pendiente')], default='aprobado+', max_length=20),
        ),
    ]
