# Generated by Django 5.2.4 on 2025-08-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0029_rename_apellido_empleados_nro_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsmproducto',
            name='cantidad_entregada',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
