# Generated by Django 5.2.6 on 2025-12-29 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0029_permiso_empresa_almacen_empleados_aprobadores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permiso_empresa_almacen',
            name='empleados_aprobadores',
        ),
        migrations.AddField(
            model_name='permiso_empresa_almacen',
            name='usuarios_aprobadores',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
