# Generated by Django 5.2.6 on 2026-01-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0030_remove_permiso_empresa_almacen_empleados_aprobadores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsm',
            name='estado_aprobacion',
            field=models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PENDIENTE', 'Pendiente')], default='APROBADO', max_length=20),
        ),
    ]
