# Generated by Django 5.2.4 on 2025-08-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0030_alter_vsmproducto_cantidad_entregada'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestro_de_materiales',
            name='cantidad_stock',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maestro_de_materiales',
            name='clase_sap',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vsm',
            name='estado_sap',
            field=models.CharField(choices=[('procesado', 'Procesado'), ('no_procesado', 'No Procesado'), ('error', 'Error')], default='no_procesado', max_length=20),
        ),
    ]
