# Generated by Django 5.2.4 on 2025-08-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0031_maestro_de_materiales_cantidad_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestro_de_materiales',
            name='cantidad_stock',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
