# Generated by Django 5.2.4 on 2025-08-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0032_alter_maestro_de_materiales_cantidad_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsm',
            name='tipo_entrega',
            field=models.CharField(choices=[('INSUMOS', 'Insumos'), ('EPP', 'EPP')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vsm',
            name='tipo_facturacion',
            field=models.CharField(choices=[('FACTURADO', 'Facturado'), ('NO_FACTURADO', 'No facturado')], max_length=20),
        ),
        migrations.DeleteModel(
            name='tipo_entrega',
        ),
        migrations.DeleteModel(
            name='tipo_facturacion',
        ),
    ]
