# Generated by Django 5.2.4 on 2025-08-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0033_alter_vsm_tipo_entrega_alter_vsm_tipo_facturacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsm',
            name='tipo_entrega',
            field=models.CharField(blank=True, choices=[('INSUMOS', 'Insumos'), ('EPP', 'EPP')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vsm',
            name='tipo_facturacion',
            field=models.CharField(blank=True, choices=[('FACTURADO', 'Facturado'), ('NO_FACTURADO', 'No facturado')], max_length=20, null=True),
        ),
    ]
