# Generated by Django 5.2.4 on 2025-09-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0034_alter_vsm_tipo_entrega_alter_vsm_tipo_facturacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilDeRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tags_productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('productos', models.ManyToManyField(related_name='tags', to='vsm_app.maestro_de_materiales')),
            ],
        ),
    ]
