# Generated by Django 5.2.4 on 2025-09-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0035_perfilderiesgo_tags_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsm',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
