# Generated by Django 5.2.4 on 2025-09-16 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0036_alter_vsm_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='nro_tarjeta',
        ),
        migrations.AddField(
            model_name='perfilderiesgo',
            name='productos',
            field=models.ManyToManyField(related_name='perfiles_de_riesgo', to='vsm_app.tags_productos'),
        ),
        migrations.CreateModel(
            name='nro_tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm_app.empleados')),
            ],
        ),
    ]
