# Generated by Django 5.2.4 on 2025-09-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm_app', '0037_remove_empleados_nro_tarjeta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nro_tarjeta',
            name='empleado',
        ),
        migrations.AddField(
            model_name='empleados',
            name='nro_tarjeta',
            field=models.ManyToManyField(blank=True, to='vsm_app.nro_tarjeta'),
        ),
    ]
